version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build  # Change this if your build command is different
artifacts:
  files:
    - '**/*'
  base-directory: build  # Update this based on where your build outputs go
